#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

# $install_dir will automatically be initialized with some decent 
# permissions by default ... however, you may need to recursively reapply
# ownership to all files such as after the ynh_setup_source step
chown -R $app:$app "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

# This should be a symetric version of what happens in the install script

ynh_restore_file --origin_path="/etc/systemd/system/$app-backup.service"
yunohost service add $app-backup --description="Run backup $app" --log="/var/log/$app/$app-backup.log"

ynh_restore_file --origin_path="/etc/systemd/system/$app-check.service"
yunohost service add $app-check --description="Check backup $app" --log="/var/log/$app/$app-check.log"

ynh_restore_file --origin_path="/etc/systemd/system/$app-check-read-data.service"
yunohost service add $app --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_restore_file --origin_path="/etc/systemd/system/$app-backup.service"
ynh_restore_file --origin_path="/etc/systemd/system/$app-check.timer"
ynh_restore_file --origin_path="/etc/systemd/system/$app-check-read-data.timer"

# Other various files...

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

ynh_restore_file --src_path="/etc/sudoers.d/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Starting systemd timers..." --weight=1

# Enable systemd timers
systemctl enable --quiet --now $app-backup.timer
systemctl enable --quiet --now $app-check.timer
systemctl enable --quiet --now $app-check-read-data.timer

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
